export const GOOGLE_FONTS = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Oswald",
  "Source Sans Pro",
  "Raleway",
  "PT Sans",
  "Merriweather",
  "Noto Sans",
  "Roboto Slab",
  "Lora",
  "Playfair Display",
  "Ubuntu",
  "Anton",
  "Poppins",
  "Bebas Neue",
  "Space Grotesk",
  "Quicksand",
  "Fira Sans",
  "Work Sans",
  "Nanum Gothic",
  "Nunito",
  "Rubik",
  "Mukta",
  "Titillium Web",
  "Barlow",
  "Inconsolata",
  "Josefin Sans",
  "Arvo",
  "Libre Baskerville",
  "Muli",
  "Dosis",
  "Cabin",
  "Abel",
  "Kanit",
  "Hind",
  "Exo 2",
  "Pacifico",
  "Lobster",
  "Dancing Script",
  "Righteous",
  "Comfortaa",
  "Orbitron",
  "Patua One",
  "Acme",
  "Kalam",
  "Shadows Into Light",
  "Amatic SC",
  "Cinzel",
  "Caveat",
  "Courgette",
  "Permanent Marker",
  "Satisfy",
  "Kaushan Script",
  "Yellowtail",
  "Great Vibes",
  "Cookie",
  "Sacramento"
];
